### ISSUE TITLE
Add Apache Camels' Bindy attributes

### ISSUE THREAD

**Issue by okgint** [urvaksh/puffer#2]
I wish pUFFER could add camel's Bindy [http://camel.apache.org/bindy.html](url) attributes like :
 - trim
 - required
 - defaultValue

And antoher important thing, Why user should extends AbstractPacket ?

**Comment by urvaksh** [comment]
Will definitely look at adding the attributes you have mentioned!

The decision to make AbstractPacket was a conscious one. I knew the drawbacks of making forcing classes to extend a framework class was not optimal, but it made things like [Composite Packets](https://github.com/urvaksh/puffer/wiki/composite-packets) very simple since any class that was being mapped always had the parse() and stringify() methods. It was a design trade off!
A longer term plan is (or was) to remove AbstractPacket and replace it with a Packet as an interface, and have the framework weave in the code, but at the time of writing, I wanted to keep it simple!

**Comment by urvaksh** [comment]
The trim attribute has been added to @PacketMessage.
The other attributes are not a fit for fixed length messages so have been left out.
